image:
  file: Dockerfile
ports:
  - port: 6080
tasks:
  - name: .NET Install
    before: |
      wget https://download.visualstudio.microsoft.com/download/pr/d3e46476-4494-41b7-a628-c517794c5a6a/6066215f6c0a18b070e8e6e8b715de0b/dotnet-sdk-6.0.402-linux-x64.tar.gz && mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-6.0.402-linux-x64.tar.gz -C $HOME/dotnet
    command: |
      gp env DOTNET_ROOT=$HOME/dotnet && gp env PATH=$PATH:$HOME/dotnet && eval $(gp env -e DOTNET_ROOT=$HOME/dotnet) && eval $(gp env -e PATH=$PATH:$HOME/dotnet)

  - name: Generate C# Project
    command: dotnet new console